<a href="https://colab.research.google.com/github/aduut/PiSchool_experiments/blob/master/NLP_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install tensorboard

In [0]:
import torch
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorboard

In [5]:
!nvidia-smi -L

GPU 0: Tesla T4 (UUID: GPU-a869d80c-c4a7-26a6-ecaf-124b54fbeb74)


In [6]:
torch.cuda.is_available()

True

In [16]:
# Create a 2D tensor 
_tensor = torch.rand((3, 3))
print(_tensor)

tensor([[0.4046, 0.8472, 0.2618],
        [0.4882, 0.9031, 0.9327],
        [0.2043, 0.8261, 0.3792]])


In [9]:
_tensor.shape

torch.Size([3, 3])

In [0]:
_ten = torch.rand(((2, 1)))

In [0]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


In [0]:
_tensor[0], _tensor[1]

(tensor([0.7475, 0.6949]), tensor([0.1548, 0.0712]))

In [22]:
_tensor.unsqueeze(0).shape

torch.Size([1, 3, 3])

In [14]:
_tensor.shape

torch.Size([3, 3])

In [0]:
_extensor = torch.unsqueeze(_tensor, 0)

In [20]:
torch.unsqueeze(_tensor, 1).shape

torch.Size([3, 1, 3])

In [23]:
torch.unsqueeze(_tensor, -1).shape

torch.Size([3, 3])

In [27]:
_extensor.shape

torch.Size([1, 3, 3])

In [0]:
__exxt = _extensor.unsqueeze(-0)

In [30]:
__exxt.shape

torch.Size([1, 1, 3, 3])

In [32]:
__exxt.unsqueeze(-1)

torch.Size([1, 1, 3, 3, 1])

In [35]:
__exxt.dim()

4

In [37]:
_extensor.dim()

3

In [39]:
# Removing the extract dimensions from the tensor
_extensor.squeeze(0).shape

torch.Size([3, 3])

In [0]:
# Random tensor of shape 5, 3 in  the interval [3,7]

rand_tensor  = torch.empty(5, 3).uniform_(3, 7)

In [44]:
rand_tensor

tensor([[5.8086, 3.7631, 4.5647],
        [5.9195, 6.5422, 6.2919],
        [5.9762, 6.2503, 4.6610],
        [3.4079, 6.3393, 3.3854],
        [5.1695, 4.0936, 5.4401]])

In [45]:
torch.randint(3, 7, (5,3))

tensor([[3, 4, 3],
        [6, 4, 3],
        [6, 3, 6],
        [5, 4, 6],
        [5, 4, 4]])

In [49]:
torch.empty(5, 3).randint_(3, 7)

AttributeError: ignored

In [48]:
dir(torch.empty)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [58]:
torch.empty(5, 3).normal_(mean=0, std=1)

tensor([[-1.2599, -0.7492, -0.9959],
        [ 0.2315,  1.0094,  0.8253],
        [-0.4922,  0.7762, -0.2430],
        [-0.4340, -0.2243, -1.4335],
        [ 1.0951,  2.0344,  0.9591]])

In [59]:
3 + torch.rand(5, 3 ) * (7-3)

tensor([[3.9274, 3.1734, 3.5356],
        [6.9964, 3.6619, 5.8608],
        [3.9700, 4.1565, 4.5244],
        [6.7438, 5.1592, 6.3118],
        [4.3790, 4.7106, 6.1055]])

In [0]:
a = torch.Tensor([1, 1, 1, 0, 1])

In [72]:
[ i for i in range(5) if a[i] !=0 ]

[0, 1, 2, 4]

In [76]:
a.nonzero()

tensor([[0],
        [1],
        [2],
        [4]])

In [0]:
x= 4 + torch.rand(5, 5) * (6)

In [91]:
torch.cat((x, x, x, x), 0)

tensor([[9.1092, 5.2545, 9.9139, 5.2454, 7.8299, 9.1092, 5.2545, 9.9139, 5.2454,
         7.8299, 9.1092, 5.2545, 9.9139, 5.2454, 7.8299, 9.1092, 5.2545, 9.9139,
         5.2454, 7.8299],
        [6.2991, 7.9085, 8.7123, 5.6051, 5.3374, 6.2991, 7.9085, 8.7123, 5.6051,
         5.3374, 6.2991, 7.9085, 8.7123, 5.6051, 5.3374, 6.2991, 7.9085, 8.7123,
         5.6051, 5.3374],
        [7.6431, 7.0454, 6.6620, 9.5377, 8.5121, 7.6431, 7.0454, 6.6620, 9.5377,
         8.5121, 7.6431, 7.0454, 6.6620, 9.5377, 8.5121, 7.6431, 7.0454, 6.6620,
         9.5377, 8.5121],
        [4.2095, 6.8091, 6.0345, 6.0277, 6.1825, 4.2095, 6.8091, 6.0345, 6.0277,
         6.1825, 4.2095, 6.8091, 6.0345, 6.0277, 6.1825, 4.2095, 6.8091, 6.0345,
         6.0277, 6.1825],
        [4.4425, 7.0762, 5.3767, 6.1046, 8.4924, 4.4425, 7.0762, 5.3767, 6.1046,
         8.4924, 4.4425, 7.0762, 5.3767, 6.1046, 8.4924, 4.4425, 7.0762, 5.3767,
         6.1046, 8.4924]])

In [0]:
a = torch.rand(3, 4, 5)
b = torch.rand(3, 5, 4)

In [87]:
torch.bmm(a,b)

tensor([[[0.4901, 0.7919, 0.5413, 1.2567],
         [0.6061, 0.8541, 0.5283, 1.4932],
         [0.7739, 1.1959, 0.7391, 1.8891],
         [0.7969, 1.0035, 0.7961, 1.3342]],

        [[0.5075, 1.5099, 1.2392, 0.9318],
         [0.6146, 1.7093, 1.0678, 1.0518],
         [0.4724, 1.7962, 1.2491, 1.3030],
         [0.4284, 1.6345, 0.5278, 1.0579]],

        [[1.2311, 1.6305, 2.3543, 1.3953],
         [2.1855, 2.3157, 3.0379, 1.5737],
         [1.2467, 1.5730, 2.1306, 0.8722],
         [1.0026, 1.3194, 1.9722, 1.4197]]])

In [90]:
x.expand(5, 20)

RuntimeError: ignored